name: Scrape latest data
    
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        curl 'https://www.bpi.com.ph/personal/bank/forex/rates' \
          | python3 parse.py | jq > bpi-forex-rates.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push